apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  type: NodePort
  selector:
    app: localstack
  ports:
    - name: http
      protocol: TCP
      port: 4566
      targetPort: 4566
      nodePort: 30666
    - name: https
      protocol: TCP
      port: 4571
      targetPort: 4571
      nodePort: 30870
